//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace beauty_salon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int id { get; set; }
        public string client { get; set; }
        public string service { get; set; }
        public string date { get; set; }
    }
}
